### ISSUE TITLE
Questionable folder name 'linear_time_sorts'

### ISSUE THREAD

**Issue by CrabOnTheBeach** [borgishmorg/algorithms#1]
Hi. I see there is a folder called 'linear_time_sorts' in root folder of this repository. But inside I can see merge_sort that, as far as I know, has complexity of O(n*log(n)) which is not quite linear.

**Comment by borgishmorg** [comment]
The folder names correspond to the names of the topics in which the corresponding algorithms are located. So, all questions to the course teacher.
